theme: jekyll-theme-cayman

title: GRIN Compiler
description: GRIN is compiler back-end for lazy and strict functional languages with whole program optimization support.

show_downloads: false
google_analytics:
github:
  repository_url: https://github.com/grin-tech/grin
